name: CI Build

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x, 8.0.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --no-restore

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
  
    - name: Setup GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
        
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true
        updateAssemblyInfo: true
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Adding the Nuget Source
      run: dotnet nuget add source "https://nuget.pkg.github.com/deveel/index.json" --name "GitHub" --username tsutomi --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Pack the Nuget Packages
      run: dotnet pack -c Release --no-build --no-restore --include-symbols --include-source --output nupkgs /p:PackageVersion ${{ env.GitVersion_SemVer }}

    - name: Publish the Nuget Packages to the GitHub Package Registry
      run: dotnet nuget push **/*.nupkg --source "GitHub" --skip-duplicate